#
##서버 포트 설정
#server.port=8000
#
##인코딩 UTF-8 설정
#server.servlet.encoding.charset=UTF-8
#server.servlet.encoding.enabled=true
#server.servlet.encoding.force=true
#server.servlet.encoding.force-request=true
#server.servlet.encoding.force-response=true
#
#server.tomcat.uri-encoding=UTF-8
#
#
##ViewResolver 설정
#spring.mvc.view.prefix=/WEB-INF/views/
#spring.mvc.view.suffix=.jsp

#=================================================

#확장자가 .yml 일때만 가능하다.
#들여쓰기 필수! 탭(4번 띄워지니까 쓰지말것) 또는 스페이스바 2번, 안하면 무조건 오류 난다
server:
  port: 8000
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
      force-request: true
      force-response: true
      
  tomcat:
    uri-encoding: UTF-8
    
spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://127.0.0.1:8001/springboot_kangmin?userUnicode=true&serverTimezone=Asia/seoul&allowMultiQueries=true
    username: root
    password: toor
#시큐리티
  security:
    user:
      name: test
      password: 1234
    oauth2:
      client:
        registration:
          google:
            client-id: 11013218846-3phpmk7pqd688j19cmi7dnemiki7c0j7.apps.googleusercontent.com
            client-secret: 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
            scope:
            - email
            - profile
          naver:
            client-id: Rjxha9PUUsaEgQ4zfDDX
            client-secret: LIC5vDx42Z
            scope:
            - email
            - name
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8000/login/oauth2/code/naver
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
    
mybatis:
  mapper-locations:
  - /mappers/*.xml


file:
  path: C:/junil/kangmin/workspace/git/SpringBoot/upload/






















